"""slack-workspaces table

Revision ID: 5929966bcdc9
Revises: 
Create Date: 2020-04-19 23:31:23.243053

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5929966bcdc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.String(length=128), nullable=False),
    sa.Column('access_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_workspace_slack_id'), 'slack_workspace', ['slack_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_workspace_slack_id'), table_name='slack_workspace')
    op.drop_table('slack_workspace')
    # ### end Alembic commands ###
